// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravellerCore.Data;

namespace TravellerCore.Migrations
{
    [DbContext(typeof(TravelDBContext))]
    partial class TravelDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravellerCore.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameCountry")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new { Id = 1, NameCountry = "Italy" },
                        new { Id = 2, NameCountry = "England" },
                        new { Id = 3, NameCountry = "Egipt" }
                    );
                });

            modelBuilder.Entity("TravellerCore.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutHotel");

                    b.Property<int?>("IdCountry");

                    b.Property<int?>("IdPicture");

                    b.Property<string>("NameHotel");

                    b.Property<decimal?>("Price");

                    b.HasKey("Id");

                    b.ToTable("Hotel");

                    b.HasData(
                        new { Id = 1, AboutHotel = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.", IdCountry = 1, IdPicture = 1, NameHotel = "Venecia", Price = 75m },
                        new { Id = 2, AboutHotel = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.", IdCountry = 1, IdPicture = 3, NameHotel = "Rome", Price = 150m },
                        new { Id = 3, AboutHotel = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.", IdCountry = 2, IdPicture = 4, NameHotel = "Washington", Price = 100m },
                        new { Id = 4, AboutHotel = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.", IdCountry = 2, IdPicture = 5, NameHotel = "London", Price = 112m }
                    );
                });

            modelBuilder.Entity("TravellerCore.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdHotel");

                    b.Property<string>("NamePicture");

                    b.HasKey("Id");

                    b.ToTable("Picture");

                    b.HasData(
                        new { Id = 1, IdHotel = 1, NamePicture = "../images/legak.png" },
                        new { Id = 2, IdHotel = 1, NamePicture = "../images/serd.png" },
                        new { Id = 3, IdHotel = 2, NamePicture = "../images/legak.png" },
                        new { Id = 4, IdHotel = 3, NamePicture = "../images/serd.png" },
                        new { Id = 5, IdHotel = 4, NamePicture = "../images/serd.png" }
                    );
                });

            modelBuilder.Entity("TravellerCore.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmountDay");

                    b.Property<DateTime?>("DateArrival");

                    b.Property<int?>("IdHotel");

                    b.HasKey("Id");

                    b.ToTable("Tour");

                    b.HasData(
                        new { Id = 1, AmountDay = 12, DateArrival = new DateTime(2019, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), IdHotel = 1 },
                        new { Id = 2, AmountDay = 10, DateArrival = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), IdHotel = 2 },
                        new { Id = 3, AmountDay = 12, DateArrival = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), IdHotel = 3 },
                        new { Id = 4, AmountDay = 14, DateArrival = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), IdHotel = 4 },
                        new { Id = 5, AmountDay = 10, DateArrival = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), IdHotel = 4 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
